CREATE TABLE IF NOT EXISTS SiteUser(
    id INT(10) PRIMARY KEY AUTO_INCREMENT,
    password VARCHAR(100) NOT NULL,
    nickName VARCHAR(100) NOT NULL,
    adminFlag TINYINT(1) NOT NULL COMMENT '0 or 1',
    deleteFlag TINYINT(1) NOT NULL COMMENT '0 or 1',
    email VARCHAR(100),
    created_at TIMESTAMP,
    login_at TIMESTAMP,
    phone_number VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS SiteUserInfo(
ID INT NOT NULL,
gender VARCHAR(10) NOT NULL,
postNumber INTEGER(7) NOT NULL,
address1 VARCHAR(100) NOT NULL,
address2 VARCHAR(100) NOT NULL,
address3 VARCHAR(100) NOT NULL,
address4 VARCHAR(100),
creditNumber INTEGER(16),
birthday DATE,
firstName1 VARCHAR(100) NOT NULL,
lastName1 VARCHAR(100) NOT NULL,
firstName2 VARCHAR(100) NOT NULL,
lastName2 VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);


